replicaCount: 2

image:
  repository: leahm90/hello-world
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
