apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
